# name: Build and Deploy
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout ğŸ›ï¸
#         uses: actions/checkout@v2
#         with:
#           persist-credentials: true

#       - name: Install, test and Build
#         run: |
#           npm install
#           # npm run lint
#           # npm run test
#           npm run build
#           npm run build-storybook

#       - name: Deploy ğŸš€
#         uses: JamesIves/github-pages-deploy-action@releases/v3
#         with:
#           ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH: gh-pages # The branch the action should deploy to.
#           FOLDER: storybook-static # folder to deploy from
#           CLEAN: true
